# Generated by Django 3.2.12 on 2022-03-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='answer41',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='chat',
            name='answer42',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='chat',
            name='chatquestion4',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='chat',
            name='correctanswer4',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
