# Generated by Django 3.2.12 on 2022-03-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20220320_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='answer51',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='chat',
            name='answer52',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='chat',
            name='chatquestion5',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='chat',
            name='correctanswer5',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
