# Generated by Django 3.2.12 on 2022-03-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DraInnManglendeOrd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correctSolution', models.TextField(max_length=30)),
                ('sentenceWord1', models.TextField(max_length=20)),
                ('sentenceWord2', models.TextField(max_length=20)),
                ('sentenceWord3', models.TextField(blank=True, max_length=20)),
                ('sentenceWord4', models.TextField(blank=True, max_length=20)),
                ('sentenceWord5', models.TextField(blank=True, max_length=20)),
                ('sentenceWord6', models.TextField(blank=True, max_length=20)),
                ('sentenceWord7', models.TextField(blank=True, max_length=20)),
                ('sentenceWord8', models.TextField(blank=True, max_length=20)),
                ('sentenceWord9', models.TextField(blank=True, max_length=20)),
                ('sentenceWord10', models.TextField(blank=True, max_length=20)),
                ('sentenceWord11', models.TextField(blank=True, max_length=20)),
                ('sentenceWord12', models.TextField(blank=True, max_length=20)),
                ('sentenceWord13', models.TextField(blank=True, max_length=20)),
                ('sentenceWord14', models.TextField(blank=True, max_length=20)),
                ('sentenceWord15', models.TextField(blank=True, max_length=20)),
                ('answerWord1', models.TextField(max_length=20)),
                ('answerWord2', models.TextField(max_length=20)),
                ('answerWord3', models.TextField(max_length=20)),
                ('answerWord4', models.TextField(max_length=20)),
                ('answerWord5', models.TextField(max_length=20)),
                ('answerWord6', models.TextField(max_length=20)),
            ],
        ),
    ]
