# Generated by Django 3.2.12 on 2022-04-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dra_inn_manglende_ord', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drainnmanglendeord',
            name='correctSolution',
        ),
        migrations.AddField(
            model_name='drainnmanglendeord',
            name='correctSolutionIndex',
            field=models.IntegerField(default=1),
        ),
    ]
