# Generated by Django 3.2.12 on 2022-04-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solutionImage', models.ImageField(upload_to='images/')),
                ('correctSolution', models.CharField(max_length=9)),
                ('letter1', models.CharField(max_length=1)),
                ('letter2', models.CharField(max_length=1)),
                ('letter3', models.CharField(max_length=1)),
                ('letter4', models.CharField(max_length=1)),
                ('letter5', models.CharField(max_length=1)),
                ('letter6', models.CharField(max_length=1)),
                ('letter7', models.CharField(max_length=1)),
                ('letter8', models.CharField(max_length=1)),
                ('letter9', models.CharField(max_length=1)),
            ],
        ),
    ]
