# Generated by Django 3.2.12 on 2022-03-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='låsoppmobil',
            name='solutionImage',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
