# Generated by Django 3.2.12 on 2022-03-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forstaelse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forstaelse',
            name='answer4',
            field=models.CharField(blank=True, choices=[('true', 'true'), ('false', 'false')], max_length=5),
        ),
        migrations.AddField(
            model_name='forstaelse',
            name='chat4',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='forstaelse',
            name='explanation4',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='forstaelse',
            name='question4',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
