# Generated by Django 3.2.12 on 2022-03-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RyddeSetninger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word1', models.CharField(max_length=20)),
                ('wordClass1', models.CharField(blank=True, choices=[('n', 'Substantiv'), ('v', 'Verb'), ('adj', 'Adjektiv'), ('adv', 'Adverb'), ('prp', 'Preposisjon'), ('conj', 'Konjuksjon'), ('subj', 'Subjuksjon'), ('det', 'Determinativ'), ('pron', 'Pronomen'), ('intj', 'Interjeksjon')], max_length=12)),
                ('word2', models.CharField(max_length=20)),
                ('wordClass2', models.CharField(blank=True, choices=[('n', 'Substantiv'), ('v', 'Verb'), ('adj', 'Adjektiv'), ('adv', 'Adverb'), ('prp', 'Preposisjon'), ('conj', 'Konjuksjon'), ('subj', 'Subjuksjon'), ('det', 'Determinativ'), ('pron', 'Pronomen'), ('intj', 'Interjeksjon')], max_length=12)),
                ('word3', models.CharField(max_length=20)),
                ('wordClass3', models.CharField(blank=True, choices=[('n', 'Substantiv'), ('v', 'Verb'), ('adj', 'Adjektiv'), ('adv', 'Adverb'), ('prp', 'Preposisjon'), ('conj', 'Konjuksjon'), ('subj', 'Subjuksjon'), ('det', 'Determinativ'), ('pron', 'Pronomen'), ('intj', 'Interjeksjon')], max_length=12)),
                ('word4', models.CharField(blank=True, max_length=20)),
                ('wordClass4', models.CharField(blank=True, choices=[('n', 'Substantiv'), ('v', 'Verb'), ('adj', 'Adjektiv'), ('adv', 'Adverb'), ('prp', 'Preposisjon'), ('conj', 'Konjuksjon'), ('subj', 'Subjuksjon'), ('det', 'Determinativ'), ('pron', 'Pronomen'), ('intj', 'Interjeksjon')], max_length=12)),
                ('word5', models.CharField(blank=True, max_length=20)),
                ('wordClass5', models.CharField(blank=True, choices=[('n', 'Substantiv'), ('v', 'Verb'), ('adj', 'Adjektiv'), ('adv', 'Adverb'), ('prp', 'Preposisjon'), ('conj', 'Konjuksjon'), ('subj', 'Subjuksjon'), ('det', 'Determinativ'), ('pron', 'Pronomen'), ('intj', 'Interjeksjon')], max_length=12)),
                ('word6', models.CharField(blank=True, max_length=20)),
                ('wordClass6', models.CharField(blank=True, choices=[('n', 'Substantiv'), ('v', 'Verb'), ('adj', 'Adjektiv'), ('adv', 'Adverb'), ('prp', 'Preposisjon'), ('conj', 'Konjuksjon'), ('subj', 'Subjuksjon'), ('det', 'Determinativ'), ('pron', 'Pronomen'), ('intj', 'Interjeksjon')], max_length=12)),
                ('word7', models.CharField(blank=True, max_length=20)),
                ('wordClass7', models.CharField(blank=True, choices=[('n', 'Substantiv'), ('v', 'Verb'), ('adj', 'Adjektiv'), ('adv', 'Adverb'), ('prp', 'Preposisjon'), ('conj', 'Konjuksjon'), ('subj', 'Subjuksjon'), ('det', 'Determinativ'), ('pron', 'Pronomen'), ('intj', 'Interjeksjon')], max_length=12)),
                ('word8', models.CharField(blank=True, max_length=20)),
                ('wordClass8', models.CharField(blank=True, choices=[('n', 'Substantiv'), ('v', 'Verb'), ('adj', 'Adjektiv'), ('adv', 'Adverb'), ('prp', 'Preposisjon'), ('conj', 'Konjuksjon'), ('subj', 'Subjuksjon'), ('det', 'Determinativ'), ('pron', 'Pronomen'), ('intj', 'Interjeksjon')], max_length=12)),
                ('word9', models.CharField(blank=True, max_length=20)),
                ('wordClass9', models.CharField(blank=True, choices=[('n', 'Substantiv'), ('v', 'Verb'), ('adj', 'Adjektiv'), ('adv', 'Adverb'), ('prp', 'Preposisjon'), ('conj', 'Konjuksjon'), ('subj', 'Subjuksjon'), ('det', 'Determinativ'), ('pron', 'Pronomen'), ('intj', 'Interjeksjon')], max_length=12)),
                ('word10', models.CharField(blank=True, max_length=20)),
                ('wordClass10', models.CharField(blank=True, choices=[('n', 'Substantiv'), ('v', 'Verb'), ('adj', 'Adjektiv'), ('adv', 'Adverb'), ('prp', 'Preposisjon'), ('conj', 'Konjuksjon'), ('subj', 'Subjuksjon'), ('det', 'Determinativ'), ('pron', 'Pronomen'), ('intj', 'Interjeksjon')], max_length=12)),
            ],
        ),
    ]
