# Generated by Django 3.2.12 on 2022-04-16 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rydde_setninger', '0001_initial'),
        ('dra_inn_manglende_ord', '0001_initial'),
        ('unlock', '0001_initial'),
        ('chat', '0001_initial'),
        ('forstaelse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('DraInnManglendeOrd1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='DraInnManglendeOrd1', to='dra_inn_manglende_ord.drainnmanglendeord')),
                ('DraInnManglendeOrd2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='DraInnManglendeOrd2', to='dra_inn_manglende_ord.drainnmanglendeord')),
                ('DraInnManglendeOrd3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='DraInnManglendeOrd3', to='dra_inn_manglende_ord.drainnmanglendeord')),
                ('DraInnManglendeOrd4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='DraInnManglendeOrd4', to='dra_inn_manglende_ord.drainnmanglendeord')),
                ('DraInnManglendeOrd5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='DraInnManglendeOrd5', to='dra_inn_manglende_ord.drainnmanglendeord')),
                ('DraInnManglendeOrd6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='DraInnManglendeOrd6', to='dra_inn_manglende_ord.drainnmanglendeord')),
                ('LåsOppMobil1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LåsOppMobil1', to='unlock.låsoppmobil')),
                ('LåsOppMobil2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LåsOppMobil2', to='unlock.låsoppmobil')),
                ('LåsOppMobil3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LåsOppMobil3', to='unlock.låsoppmobil')),
                ('LåsOppMobil4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LåsOppMobil4', to='unlock.låsoppmobil')),
                ('LåsOppMobil5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LåsOppMobil5', to='unlock.låsoppmobil')),
                ('LåsOppMobil6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LåsOppMobil6', to='unlock.låsoppmobil')),
                ('chat1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat1', to='chat.chat')),
                ('chat2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat2', to='chat.chat')),
                ('chat3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat3', to='chat.chat')),
                ('chat4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat4', to='chat.chat')),
                ('chat5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat5', to='chat.chat')),
                ('chat6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat6', to='chat.chat')),
                ('forstaelse1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forstaelse1', to='forstaelse.forstaelse')),
                ('forstaelse2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forstaelse2', to='forstaelse.forstaelse')),
                ('forstaelse3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forstaelse3', to='forstaelse.forstaelse')),
                ('forstaelse4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forstaelse4', to='forstaelse.forstaelse')),
                ('forstaelse5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forstaelse5', to='forstaelse.forstaelse')),
                ('forstaelse6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forstaelse6', to='forstaelse.forstaelse')),
                ('ryddeSetninger1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ryddeSetninger1', to='rydde_setninger.ryddesetninger')),
                ('ryddeSetninger2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ryddeSetninger2', to='rydde_setninger.ryddesetninger')),
                ('ryddeSetninger3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ryddeSetninger3', to='rydde_setninger.ryddesetninger')),
                ('ryddeSetninger4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ryddeSetninger4', to='rydde_setninger.ryddesetninger')),
                ('ryddeSetninger5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ryddeSetninger5', to='rydde_setninger.ryddesetninger')),
                ('ryddeSetninger6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ryddeSetninger6', to='rydde_setninger.ryddesetninger')),
            ],
        ),
    ]
