# Generated by Django 3.2.12 on 2022-04-17 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fill_in_word', '0001_initial'),
        ('chat', '0001_initial'),
        ('sort_sentence', '0001_initial'),
        ('unlock', '0001_initial'),
        ('comprehension', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('chat1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat1', to='chat.chat')),
                ('chat2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat2', to='chat.chat')),
                ('chat3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat3', to='chat.chat')),
                ('chat4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat4', to='chat.chat')),
                ('chat5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat5', to='chat.chat')),
                ('chat6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat6', to='chat.chat')),
                ('comprehension1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprehension1', to='comprehension.comprehension')),
                ('comprehension2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprehension2', to='comprehension.comprehension')),
                ('comprehension3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprehension3', to='comprehension.comprehension')),
                ('comprehension4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprehension4', to='comprehension.comprehension')),
                ('comprehension5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprehension5', to='comprehension.comprehension')),
                ('comprehension6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprehension6', to='comprehension.comprehension')),
                ('fillInWord1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fillInWord1', to='fill_in_word.fillinword')),
                ('fillInWord2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fillInWord2', to='fill_in_word.fillinword')),
                ('fillInWord3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fillInWord3', to='fill_in_word.fillinword')),
                ('fillInWord4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fillInWord4', to='fill_in_word.fillinword')),
                ('fillInWord5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fillInWord5', to='fill_in_word.fillinword')),
                ('fillInWord6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fillInWord6', to='fill_in_word.fillinword')),
                ('sortSentence1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sortSentence1', to='sort_sentence.sortsentence')),
                ('sortSentence2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sortSentence2', to='sort_sentence.sortsentence')),
                ('sortSentence3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sortSentence3', to='sort_sentence.sortsentence')),
                ('sortSentence4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sortSentence4', to='sort_sentence.sortsentence')),
                ('sortSentence5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sortSentence5', to='sort_sentence.sortsentence')),
                ('sortSentence6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sortSentence6', to='sort_sentence.sortsentence')),
                ('unlock1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlock1', to='unlock.unlock')),
                ('unlock2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlock2', to='unlock.unlock')),
                ('unlock3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlock3', to='unlock.unlock')),
                ('unlock4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlock4', to='unlock.unlock')),
                ('unlock5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlock5', to='unlock.unlock')),
                ('unlock6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlock6', to='unlock.unlock')),
            ],
        ),
    ]
