# Generated by Django 3.2.12 on 2022-04-01 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sets',
            name='description',
        ),
    ]
