# Generated by Django 3.2.12 on 2022-03-20 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forstaelse', '0002_auto_20220320_1810'),
        ('chat', '0003_auto_20220320_2043'),
        ('rydde_setninger', '0002_auto_20220320_1810'),
        ('unlock', '0001_initial'),
        ('dra_inn_manglende_ord', '0001_initial'),
        ('sets', '0002_auto_20220320_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='sets',
            name='DraInnManglendeOrd6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='DraInnManglendeOrd6', to='dra_inn_manglende_ord.drainnmanglendeord'),
        ),
        migrations.AddField(
            model_name='sets',
            name='LåsOppMobil6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LåsOppMobil6', to='unlock.låsoppmobil'),
        ),
        migrations.AddField(
            model_name='sets',
            name='chat6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat6', to='chat.chat'),
        ),
        migrations.AddField(
            model_name='sets',
            name='forstaelse6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forstaelse6', to='forstaelse.forstaelse'),
        ),
        migrations.AddField(
            model_name='sets',
            name='ryddeSetninger6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ryddeSetninger6', to='rydde_setninger.ryddesetninger'),
        ),
    ]
