# Generated by Django 3.2.12 on 2022-04-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comprehension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('true', 'true'), ('false', 'false')], max_length=5)),
                ('chat', models.CharField(max_length=1000)),
                ('question', models.CharField(max_length=1000)),
                ('explanation', models.CharField(max_length=1000)),
            ],
        ),
    ]
